```{css}

@import url('https://fonts.googleapis.com/css2?family=Gidole&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk&display=swap');

body {
  color: #000000;
  background-image:         url("https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fillustrations%2Fcharts-background&psig=AOvVaw1sV6-nd2MkGgQEpIhqZpSz&ust=1743665521921000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJjapbzquIwDFQAAAAAdAAAAABAE");
  padding-bottom: 25px;
}

h1 {
  color: #000000;
  border-style: dashed;
  font-family: 'Gidole';
}

h2 {
  color: #000000;
  font-family: 'Gidole';
}

h3 {
  color: #000000;
  font-family: 'Gidole';
}

h4 {
  color: #000000;
  font-family: 'Gidole';
}
  
p {
  color: #000000;
  background-color: #d52f13;;
  border-style: dashed;
  padding: 20px 5px 20px 5px;
  font-family: 'Gidole';
} 

a {
  color: #000000;
  font-family: 'Gidole';
}

```

## Analysing some key features of these songs

For this project, I decided to listen to four radio stations (Flava, Channel X, ZM, The Hits) and note each song that played on a station. I switched between each of the stations in the aforementioned order about every six minutes and noted each song that was playing at the time. A while after that, I then put in each of the 40 songs I noted through a Google form, noting their title, artist/s, release date, genre, radio station, peak chart position, and no of streams on Spotify.

As part of analysing the data that I collected, I decided to find out which song had the most streams on Spotify, the songs with the shortest title, the oldest song in my playlist, looking at how popular each of the genres are, and looking at the Spotify streams for each song, grouped by radio station it was heard on.

```{r}

#loading those three special packages
library(magick)
library(tidyverse)
library(lubridate)

#creating an object that holds the data I collected in my Google Sheet
csv_file = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRoFDtuwgf9qe8prM37JTIYOia3rPBGxo5TXZ3UPcXLw8kS939ugXozMVbUc8CWOy2PcH7Ha1pc0uAU/pub?output=csv"

#using read_csv to put the data into a data frame
logged_data = read_csv(csv_file)

#renaming all the variables in my data frame to something more appropriate
latest_data = logged_data %>%
  rename(timestamp = 1,
         song_title = 2,
         artist_name = 3,
         release_date = 4,
         genre = 5,
         radio_station = 6,
         peak_position = 7,
         spotify_streams = 8)

#getting r to show a preview of my data frame
glimpse(latest_data)

#analysing what the most streamed song in my playlist is
latest_data$spotify_streams[1 : 40]
paste("The most streamed song in my playlist has been streamed",
      max(latest_data$spotify_streams), "times")

#analysing what songs in my playlist have the shortest title
#three songs have the shortest title!
shortest_song_title = latest_data$song_title %>% nchar() %>% min()
shortest_song = nchar(latest_data$song_title) == shortest_song_title
paste("The song with the shortest title is",
      latest_data$song_title[shortest_song])

#analysing what the oldest song in my playlist is
#using the dmy function from lubridate package to convert dates into yyyy-mm-dd format
latest_data$release_date[1 : 40]
new_release_date = dmy(latest_data$release_date)
paste("The oldest song in my playlist was released on",
      min(new_release_date))

#creating a bar plot to analyse genre in my playlist
ggplot(data = latest_data) +
  geom_bar(aes(y = genre),
           fill = "#a7d3a5") +
  labs(title = "Popularity of Genre",
       subtitle = "By number of songs with that genre",
       x = "no of songs",
       y = "genre")

#creating a bar plot to analyse all the songs in my playlist by how many times they have been streamed
#the bars are coloured according to what station they played on
latest_data %>%
  ggplot() +
    geom_bar(aes(x = song_title, y = spotify_streams, fill = radio_station),
             stat = 'identity') +
    labs(title = "Number of Streams by Radio Station",
         subtitle = "Songs are listed by alphabetical order",
         caption = "Source: Spotify",
         x = "song",
         y = "no of streams") +
    guides(fill=guide_legend(title="Radio Station")) +
    theme(axis.text.x = element_blank())

#i have decided to use all of the code relating to analysing parts of my data
#from the most streamed song analysis to the most streamed songs bar plot

```
